# DISTANT INSTANCE (Production)
REMOTE_URL=""
REMOTE_ROOTDIR=""
REMOTE_FTP_HOST=""
REMOTE_FTP_USER=""
REMOTE_SQL_HOST=""
REMOTE_SQL_USER=""
REMOTE_SQL_PASSWORD=""
REMOTE_SQL_DATABASE=""

# MAGENTO SPECIFICS
ADMIN_PATH="admin"
