# DISTANT INSTANCE (Production)
# All _DIR must contain a trailing slash
REMOTE_URL_UNSECURE=""
REMOTE_URL_SECURE=""
REMOTE_URL=${REMOTE_URL_UNSECURE}
REMOTE_ROOTDIR=""
REMOTE_FTP_HOST=""
REMOTE_FTP_USER=""
REMOTE_SQL_HOST=""
REMOTE_SQL_USER=""
REMOTE_SQL_PASSWORD=""
REMOTE_SQL_DATABASE=""

SKIN_DIR=""

# MAGENTO SPECIFICS
REMOTE_ADMIN_PATH="admin"
