# LOCAL INSTANCE (Maman)
LOCAL_URL="_LOCAL_URL"
LOCAL_ROOTDIR="_LOCAL_ROOTDIR"
LOCAL_FTP_HOST="_LOCAL_FTP_HOST"
LOCAL_FTP_USER="_LOCAL_FTP_USER"
LOCAL_SQL_HOST="_LOCAL_SQL_HOST"
LOCAL_SQL_USER="_LOCAL_SQL_USER"
LOCAL_SQL_PASSWORD="_LOCAL_SQL_PASSWORD"
LOCAL_SQL_DATABASE="_LOCAL_SQL_DATABASE"

# MAGENTO SPECIFICS
ADMIN_PATH="admin"
